

<?php $__env->startSection('content'); ?>
<section class="border-b border-slate-800 bg-[linear-gradient(120deg,#082f49,#0f172a_55%,#431407)]">
    <div class="mx-auto max-w-6xl px-5 py-20 sm:py-28"><p class="text-sm font-bold uppercase tracking-[0.2em] text-cyan-300">The story</p><h1 class="mt-5 max-w-3xl text-4xl font-bold tracking-tight text-white sm:text-6xl">Make the next useful action obvious.</h1><p class="mt-6 max-w-2xl text-lg leading-8 text-slate-300">Enterprise Tasks began with a simple observation: personal work gets harder to finish when the system around it is noisy. The product keeps capture, progress, and governance in their proper places.</p></div>
</section>
<section class="mx-auto grid max-w-6xl gap-12 px-5 py-16 sm:grid-cols-3"><div><h2 class="text-xl font-bold text-white">Mission</h2><p class="mt-3 leading-7 text-slate-400">Give people a calm, private place to move work forward.</p></div><div><h2 class="text-xl font-bold text-white">Principles</h2><p class="mt-3 leading-7 text-slate-400">Ownership, understandable states, and accountable administration guide every decision.</p></div><div><h2 class="text-xl font-bold text-white">People</h2><p class="mt-3 leading-7 text-slate-400">A small product-minded team focused on reliable workflows rather than feature noise.</p></div></section>
<section class="bg-slate-900"><div class="mx-auto flex max-w-6xl flex-col gap-6 px-5 py-14 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="text-2xl font-bold text-white">See how the workspace works</h2><p class="mt-2 text-slate-400">Explore the product capabilities or start with your account.</p></div><a href="<?php echo e(route('capabilities')); ?>" class="inline-flex w-fit rounded-lg bg-cyan-500 px-5 py-3 font-bold text-slate-950 hover:bg-cyan-300">Explore capabilities</a></div></section>
<?php $__env->stopSection(); ?>
<?php echo $__env->make('layouts.public', ['title' => 'About', 'description' => 'Learn why Enterprise Tasks exists and how it keeps personal work and administrative governance clear.'], array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH D:\Projects\task-enterprise-api\resources\views\public\about.blade.php ENDPATH**/ ?>